Mistcity_PokemonCenter_2F_MapScripts::
	.byte 0


Mistcity_PokemonCenter_2F_Red_Convo::
	lock
	faceplayer
	setspeaker Mistcity_PokemonCenter_2F_Red_Convo_Text_0
	msgbox Mistcity_PokemonCenter_2F_Red_Convo_Text_1
	waitmessage
	release
	end


Mistcity_PokemonCenter_2F_Red_Convo_Text_0:
	.string "GAME MAKER$"

Mistcity_PokemonCenter_2F_Red_Convo_Text_1:
	.string "Hi there! Well done on getting to the\n"
	.string "third town.\p"
	.string "My inspiration for this map and it\n"
	.string "surroundings is the cloud forest in\l"
	.string "Costa Rica.\p"
	.string "This forest, located high up the\n"
	.string "mountains, provides it's own rain and is\l"
	.string "really up in the clouds all the time.\p"
	.string "While being there I saw so many\n"
	.string "different species of animals.\p"
	.string "Everytime we went on a wildlife tour we\n"
	.string "saw something new and exciting.\p"
	.string "Hopefully this is the case in Mist City\n"
	.string "as well.\p"
	.string "The cool thing is that I modelled Daan,\n"
	.string "the protecter of the forest, after\l"
	.string "myself.\p"
	.string "My real life job is being a biodiversity\n"
	.string "advisor for a large construction\l"
	.string "company in europe.\p"
	.string "I'm trying to make our construction\n"
	.string "projects nature postive, and our supply\l"
	.string "chains nature damage free.\p"
	.string "This mission is close to my heart,\n"
	.string "hopefully that passion shines through\l"
	.string "in this map of the game.\p"
	.string "Enjoy!$"
