MarshDukeCity_MapScripts::
	.byte 0


Marshduke_Library_Sign::
# 4 "data/maps/MarshDukeCity/scripts.pory"
	lock
# 5 "data/maps/MarshDukeCity/scripts.pory"
	msgbox Marshduke_Library_Sign_Text_0, MSGBOX_SIGN
# 6 "data/maps/MarshDukeCity/scripts.pory"
	waitmessage
# 7 "data/maps/MarshDukeCity/scripts.pory"
	release
	end


Marshduke_Library_Sign_Text_0:
# 5 "data/maps/MarshDukeCity/scripts.pory"
	.string "- Marshduke Library -\n"
	.string "WE WRITE TO REMEMBER FOR OURSELVES.$"
