#ifndef GUARD_CONSTANTS_MAP_TYPES_H
#define GUARD_CONSTANTS_MAP_TYPES_H

enum MapType
{
    MAP_TYPE_NONE,
    MAP_TYPE_TOWN,
    MAP_TYPE_CITY,
    MAP_TYPE_ROUTE,
    MAP_TYPE_UNDERGROUND,
    MAP_TYPE_UNDERWATER,
    MAP_TYPE_OCEAN_ROUTE,
    MAP_TYPE_UNKNOWN, // Not used by any map.
    MAP_TYPE_INDOOR,
    MAP_TYPE_SECRET_BASE,
};

enum MapBattleScene
{
    MAP_BATTLE_SCENE_NORMAL,
    MAP_BATTLE_SCENE_GYM,
    MAP_BATTLE_SCENE_MAGMA,
    MAP_BATTLE_SCENE_AQUA,
    MAP_BATTLE_SCENE_SIDNEY,
    MAP_BATTLE_SCENE_PHOEBE,
    MAP_BATTLE_SCENE_GLACIA,
    MAP_BATTLE_SCENE_DRAKE,
    MAP_BATTLE_SCENE_FRONTIER,
    MAP_BATTLE_SCENE_WILL_HNS,
    MAP_BATTLE_SCENE_KOGA_HNS,
    MAP_BATTLE_SCENE_BRUNO_HNS,
    MAP_BATTLE_SCENE_KAREN_HNS,
    MAP_BATTLE_SCENE_LANCE_HNS,
    MAP_BATTLE_SCENE_BLUE_BUILDING,

    // ShinyKrabby: terrain-type map battle scenes (ported from custom maps).
    // Not dispatched through this field at runtime - the actual battle
    // background for these maps is chosen via sMapDefaultEnvironments in
    // battle_setup.c. These values only need to exist so the map header's
    // battle_scene byte field has something valid to compile to.
    MAP_BATTLE_SCENE_CAVE,
    MAP_BATTLE_SCENE_DESERT,
    MAP_BATTLE_SCENE_INDOOR,
    MAP_BATTLE_SCENE_LONG_GRASS,
    MAP_BATTLE_SCENE_MOUNTAIN,
    MAP_BATTLE_SCENE_RED_CAVE,
    MAP_BATTLE_SCENE_SAND,
    MAP_BATTLE_SCENE_SNOW,
    MAP_BATTLE_SCENE_SNOW_CAVE,
    MAP_BATTLE_SCENE_TALL_GRASS,
};

#define MAP_BATTLE_SCENE_INDOOR_1 MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_INDOOR_2 MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LORELEI  MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_BRUNO    MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_AGATHA   MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LANCE    MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LINK     MAP_BATTLE_SCENE_NORMAL

#endif  // GUARD_CONSTANTS_MAP_TYPES_H
