#ifndef GUARD_CONSTANTS_OPPONENTS_SK_H
#define GUARD_CONSTANTS_OPPONENTS_SK_H

// ShinyKrabby (Tessera) trainer ids. TRAINERS_COUNT_HNS (opponents_hns.h) derives
// from SK_TRAINERS_END, so growing NUM_SK_TRAINERS is the only thing needed to add
// more trainers here - no need to touch opponents_hns.h.
#define SK_TRAINERS_START                              619
#define NUM_SK_TRAINERS                               128
#define SK_TRAINERS_END                                (SK_TRAINERS_START + NUM_SK_TRAINERS - 1)

// ShinyKrabby custom trainers (ported from custom maps)
#define TRAINER_ADDY                                 (SK_TRAINERS_START + 0)
#define TRAINER_ALFRED                               (SK_TRAINERS_START + 1)
#define TRAINER_ANONA                                (SK_TRAINERS_START + 2)
#define TRAINER_ARIELLE                              (SK_TRAINERS_START + 3)
#define TRAINER_BARRY_DEEPCLOUDFOREST                (SK_TRAINERS_START + 4)
#define TRAINER_BATTLE_GIRL_SERA                     (SK_TRAINERS_START + 5)
#define TRAINER_BIKER_FRLG_AXEL                      (SK_TRAINERS_START + 6)
#define TRAINER_BIKER_FRLG_COLT                      (SK_TRAINERS_START + 7)
#define TRAINER_BIKER_FRLG_GRIT                      (SK_TRAINERS_START + 8)
#define TRAINER_BIKER_FRLG_SEAR                      (SK_TRAINERS_START + 9)
#define TRAINER_BIKER_FRLG_SKYE                      (SK_TRAINERS_START + 10)
#define TRAINER_BIKER_REX                            (SK_TRAINERS_START + 11)
#define TRAINER_BLACK_BELT_KENZO                     (SK_TRAINERS_START + 12)
#define TRAINER_BRAM                                 (SK_TRAINERS_START + 13)
#define TRAINER_BUG_CATCHER_JASPER                   (SK_TRAINERS_START + 14)
#define TRAINER_CHUCKIE                              (SK_TRAINERS_START + 15)
#define TRAINER_DAVID_HEARTFIELD                     (SK_TRAINERS_START + 16)
#define TRAINER_DENTON                               (SK_TRAINERS_START + 17)
#define TRAINER_DERYCK                               (SK_TRAINERS_START + 18)
#define TRAINER_EDGARD                               (SK_TRAINERS_START + 19)
#define TRAINER_FACULTY_2F_GRUNT                     (SK_TRAINERS_START + 20)
#define TRAINER_FACULTY_2F_SCIENTIST_1               (SK_TRAINERS_START + 21)
#define TRAINER_FACULTY_2F_SCIENTIST_2               (SK_TRAINERS_START + 22)
#define TRAINER_FACULTY_GUARD_B1F_1                  (SK_TRAINERS_START + 23)
#define TRAINER_FACULTY_GUARD_B1F_2                  (SK_TRAINERS_START + 24)
#define TRAINER_FACULTY_OFFICIAL_1                   (SK_TRAINERS_START + 25)
#define TRAINER_FACULTY_OFFICIAL_2                   (SK_TRAINERS_START + 26)
#define TRAINER_FACULTY_OFFICIAL_3                   (SK_TRAINERS_START + 27)
#define TRAINER_FACULTY_RECTOR                       (SK_TRAINERS_START + 28)
#define TRAINER_FACULTY_SCIENTIST_1                  (SK_TRAINERS_START + 29)
#define TRAINER_FACULTY_SCIENTIST_2                  (SK_TRAINERS_START + 30)
#define TRAINER_FACULTY_SCIENTIST_FACTORY1           (SK_TRAINERS_START + 31)
#define TRAINER_GABRIELLE                            (SK_TRAINERS_START + 32)
#define TRAINER_GRUNT_FACULTY_1                      (SK_TRAINERS_START + 33)
#define TRAINER_GRUNT_FACULTY_2                      (SK_TRAINERS_START + 34)
#define TRAINER_GRUNT_FACULTY_CLOUDFOREST_1          (SK_TRAINERS_START + 35)
#define TRAINER_GRUNT_FACULTY_CLOUDFOREST_2          (SK_TRAINERS_START + 36)
#define TRAINER_GRUNT_FACULTY_CLOUDFOREST_3          (SK_TRAINERS_START + 37)
#define TRAINER_GRUNT_FACULTY_CLOUDFOREST_4          (SK_TRAINERS_START + 38)
#define TRAINER_HARDY                                (SK_TRAINERS_START + 39)
#define TRAINER_HIKER_ALDRIC                         (SK_TRAINERS_START + 40)
#define TRAINER_HIKER_BOWEN                          (SK_TRAINERS_START + 41)
#define TRAINER_HIKER_CORIN                          (SK_TRAINERS_START + 42)
#define TRAINER_HIKER_DANE                           (SK_TRAINERS_START + 43)
#define TRAINER_HIKER_WADE                           (SK_TRAINERS_START + 44)
#define TRAINER_INTERVIEWER_LANE                     (SK_TRAINERS_START + 45)
#define TRAINER_JEFFRY                               (SK_TRAINERS_START + 46)
#define TRAINER_KEGAN                                (SK_TRAINERS_START + 47)
#define TRAINER_KINDLER_OPAL                         (SK_TRAINERS_START + 48)
#define TRAINER_LASS_ELENA                           (SK_TRAINERS_START + 49)
#define TRAINER_LASS_QUINN                           (SK_TRAINERS_START + 50)
#define TRAINER_LAWSON                               (SK_TRAINERS_START + 51)
#define TRAINER_LAYTON                               (SK_TRAINERS_START + 52)
#define TRAINER_LINTON                               (SK_TRAINERS_START + 53)
#define TRAINER_LIONSARCH_HIKER_1                    (SK_TRAINERS_START + 54)
#define TRAINER_LIONSARCH_HIKER_2                    (SK_TRAINERS_START + 55)
#define TRAINER_LIONSARCH_HIKER_3                    (SK_TRAINERS_START + 56)
#define TRAINER_LIONSARCH_HIKER_4                    (SK_TRAINERS_START + 57)
#define TRAINER_LIONSARCH_HIKER_5                    (SK_TRAINERS_START + 58)
#define TRAINER_LIONSARCH_LEADER1                    (SK_TRAINERS_START + 59)
#define TRAINER_LIONSARCH_LEADER2                    (SK_TRAINERS_START + 60)
#define TRAINER_MART                                 (SK_TRAINERS_START + 61)
#define TRAINER_MILES                                (SK_TRAINERS_START + 62)
#define TRAINER_NEELY                                (SK_TRAINERS_START + 63)
#define TRAINER_NEWTON                               (SK_TRAINERS_START + 64)
#define TRAINER_PETELONGFELLOW                       (SK_TRAINERS_START + 65)
#define TRAINER_POKEMANIAC_EDGAR                     (SK_TRAINERS_START + 66)
#define TRAINER_ROB                                  (SK_TRAINERS_START + 67)
#define TRAINER_ROYSTON                              (SK_TRAINERS_START + 68)
#define TRAINER_SCIENTIST_WARREN                     (SK_TRAINERS_START + 69)
#define TRAINER_TERESA                               (SK_TRAINERS_START + 70)
#define TRAINER_TRIATHLETE_F_DUNE                    (SK_TRAINERS_START + 71)
#define TRAINER_TRIATHLETE_F_FERN                    (SK_TRAINERS_START + 72)
#define TRAINER_TRIATHLETE_F_MIRA                    (SK_TRAINERS_START + 73)
#define TRAINER_TRIATHLETE_F_VELA                    (SK_TRAINERS_START + 74)
#define TRAINER_TRIATHLETE_F_WREN                    (SK_TRAINERS_START + 75)
#define TRAINER_TRIATHLETE_M_HOLT                    (SK_TRAINERS_START + 76)
#define TRAINER_TRIATHLETE_M_JUDE                    (SK_TRAINERS_START + 77)
#define TRAINER_TRIATHLETE_M_PIKE                    (SK_TRAINERS_START + 78)
#define TRAINER_TRIATHLETE_M_REED                    (SK_TRAINERS_START + 79)
#define TRAINER_WILFRED                              (SK_TRAINERS_START + 80)

// Adopted from leftover vanilla placeholder scripts (same names/parties, own ids)
#define TRAINER_CALVIN_1_SK                          (SK_TRAINERS_START + 81)
#define TRAINER_LYLE_SK                              (SK_TRAINERS_START + 82)
#define TRAINER_TIANA_SK                             (SK_TRAINERS_START + 83)
#define TRAINER_WINSTON_1_SK                         (SK_TRAINERS_START + 84)
#define TRAINER_PRESTON_SK                           (SK_TRAINERS_START + 85)
#define TRAINER_BLAKE_SK                             (SK_TRAINERS_START + 86)
#define TRAINER_MAURA_SK                             (SK_TRAINERS_START + 87)
#define TRAINER_SAMANTHA_SK                          (SK_TRAINERS_START + 88)
#define TRAINER_VIRGIL_SK                            (SK_TRAINERS_START + 89)
#define TRAINER_HANNAH_SK                            (SK_TRAINERS_START + 90)
#define TRAINER_NATE_SK                              (SK_TRAINERS_START + 91)
#define TRAINER_SYLVIA_SK                            (SK_TRAINERS_START + 92)
#define TRAINER_CLIFFORD_SK                          (SK_TRAINERS_START + 93)
#define TRAINER_MACEY_SK                             (SK_TRAINERS_START + 94)
#define TRAINER_KATHLEEN_SK                          (SK_TRAINERS_START + 95)
#define TRAINER_NICHOLAS_SK                          (SK_TRAINERS_START + 96)

// Tessera NPCs that previously borrowed Emerald trainer ids.
#define TRAINER_RICK_MAASJE_SK                       (SK_TRAINERS_START + 97)
#define TRAINER_ALLEN_MAASJE_SK                      (SK_TRAINERS_START + 98)
#define TRAINER_IVAN_MAASJE_SK                       (SK_TRAINERS_START + 99)
#define TRAINER_JAMES_ROUTE01_SK                     (SK_TRAINERS_START + 100)
#define TRAINER_MARCEL_ROUTE03_SK                    (SK_TRAINERS_START + 101)
#define TRAINER_ALBERTO_ROUTE03_SK                   (SK_TRAINERS_START + 102)
#define TRAINER_ED_ROUTE03_SK                        (SK_TRAINERS_START + 103)
#define TRAINER_ALBERT_EAST_LION_SK                  (SK_TRAINERS_START + 104)
#define TRAINER_SAMUEL_EAST_LION_SK                  (SK_TRAINERS_START + 105)
#define TRAINER_VITO_EAST_LION_SK                    (SK_TRAINERS_START + 106)
#define TRAINER_MADS_MINING_SK                       (SK_TRAINERS_START + 107)
#define TRAINER_AD_MINING_SK                         (SK_TRAINERS_START + 108)
#define TRAINER_OWEN_MINING_SK                       (SK_TRAINERS_START + 109)
#define TRAINER_WARREN_MINING_SK                     (SK_TRAINERS_START + 110)
#define TRAINER_BARRY_MINING_SK                      (SK_TRAINERS_START + 111)
#define TRAINER_LEAH_ROUTE04_SK                      (SK_TRAINERS_START + 112)
#define TRAINER_FREDRICK_ROUTE04_SK                  (SK_TRAINERS_START + 113)
#define TRAINER_MATT_ROUTE04_SK                      (SK_TRAINERS_START + 114)
#define TRAINER_DAISY_ROUTE04_SK                     (SK_TRAINERS_START + 115)
#define TRAINER_ZANDER_ROUTE04_SK                    (SK_TRAINERS_START + 116)
#define TRAINER_ARCHIE_ROUTE04_SK                    (SK_TRAINERS_START + 117)
#define TRAINER_RANDALL_ROUTE05_SK                   (SK_TRAINERS_START + 118)
#define TRAINER_PARKER_ROUTE05_SK                    (SK_TRAINERS_START + 119)
#define TRAINER_GEORGE_ROUTE05_SK                    (SK_TRAINERS_START + 120)
#define TRAINER_BERKE_ROUTE05_SK                     (SK_TRAINERS_START + 121)
#define TRAINER_BRAXTON_ROUTE05_SK                   (SK_TRAINERS_START + 122)
#define TRAINER_VINCENT_ROUTE05_SK                   (SK_TRAINERS_START + 123)
#define TRAINER_CHARLIE_UPANA_SK                     (SK_TRAINERS_START + 124)
#define TRAINER_LEROY_WEST_LION_SK                  (SK_TRAINERS_START + 125)
#define TRAINER_WILTON_WEST_LION_SK                 (SK_TRAINERS_START + 126)
#define TRAINER_EDGAR_WEST_LION_SK                  (SK_TRAINERS_START + 127)

#endif // GUARD_CONSTANTS_OPPONENTS_SK_H
