gText_Oak_Welcome::
	.string "Is this thing on? Can you hear me?\p"
	.string "Camera's frozen. There, fixed it.\p"
	.string "GOOD DAY, ASPIRING INTERN!\p"
	.string "CAN YOU SEE MY FACE PROPERLY?\p"
	.string "Doesn't matter, doesn't matter...\p"
	.string "ARE YOU CURRENTLY UNEMPLOYED?\p"
	.string "Perfect! I mean.. no worries!\p"
	.string "I, Professor BIRDS, am conducting\n"
	.string "video interviews for one\l"
	.string "unpaid research position at my\l"
	.string "laboratory in ERP TOWN.\p"
	.string "The work is IMPORTANT.\n"
	.string "The subsidy is even more..\p"
	.string "I mean! The EXPERIENCE is\n"
	.string "invaluable! Ahem.\p"
	.string "As compensation I will provide you\n"
	.string "with a POKéMON. Free of charge.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Behold! The legendary, magnificent and\n"
	.string "amazing Magikarp!\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "It's rare. Super rare actually.\p"
	.string "Don't look it up...\p"
	.string "Anyways! My lab is engaged in research\n"
	.string "of the highest fundable importance.\p"
	.string "I cannot tell you what it's really\n"
	.string "for. Not yet.\p"
	.string "What I CAN tell you is that\n"
	.string "it involves PIG SENSORS.\p"
	.string "They detect things.\n"
	.string "Very grant-worthy things.\p"
	.string "Things that qualify for GOVERNMENT\n"
	.string "SUBSIDIES that GOVERNMENTS don't\l"
	.string "look too closely at.\p"
	.string "That is all I will say. On record.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Anyways. I trust you're now\n"
	.string "sufficiently convinced of my\l"
	.string "legitimacy as an employer.\p"
	.string "I'm going to need some information.\n"
	.string "for the subsidy applica... \l"
	.string "I mean your CONTRACT, of course!\p"
	.string "Slip of the tongue. Happens\n"
	.string "constantly during audits.\p"
	.string "$"

gText_Oak_BoyOrGirl::
	.string "So. Are you Male or Female?$"

gText_Oak_WhatChallenge::
	.string "What challenge are you\n"
	.string "expecting?$"

gText_Oak_ChallengeSelected::
	.string "Noted. That goes straight\n"
	.string "into your personnel file.$"

gText_Oak_WhatsYourName::
	.string "Good. Now I need your name on the\n"
	.string "applica... grant... CONTRACT.\p"
	.string "The REAL one. Not your TikTok username.\n"
	.string "The auditors don't like usernames.\p"
	.string "I will NOT have that nonsense\n"
	.string "attached to my funding.\p"
	.string "Also HR needs it.\n"
	.string "Coincindence, I'm also the HR\l"
	.string "department!\p"
	.string "What shall I put down on the\n"
	.string "subsidy... the CONTRACT!\p"
	.string "$"

gText_Oak_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "Fine. {PLAYER}.\n"
	.string "You're hired.\p"
	.string "Unpaid.\n"
	.string "Officially an intern. Don't tell\l"
	.string "the auditors otherwise.\p"
	.string "Be at my lab in ERP TOWN.\n"
	.string "July 14th.\p"
	.string "7AM sharp.\n"
	.string "Just before I go to sleep.\p"
	.string "Oh, and do not go through the door\n"
	.string "at the back.\p"
	.string "Because there is no door at the\n"
	.string "back. There never was.\l"
	.string "Forget I mentioned a door.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "- 6 MONTHS LATER - \n"
	.string "- July 14th, 7 AM. -\p"
	.string "$"
