Maasje_PokemonCenter_2F_MapScripts::
	.byte 0


Maasje_PokemonCenter_2F_Red::
# 4 "data/maps/Maasje_PokemonCenter_2F/scripts.pory"
	lock
# 5 "data/maps/Maasje_PokemonCenter_2F/scripts.pory"
	faceplayer
# 6 "data/maps/Maasje_PokemonCenter_2F/scripts.pory"
	msgbox Maasje_PokemonCenter_2F_Red_Text_0
# 7 "data/maps/Maasje_PokemonCenter_2F/scripts.pory"
	waitmessage
# 8 "data/maps/Maasje_PokemonCenter_2F/scripts.pory"
	release
	return


Maasje_PokemonCenter_2F_Red_Text_0:
# 6 "data/maps/Maasje_PokemonCenter_2F/scripts.pory"
	.string "Hi there, I'm the maker of the game.\p"
	.string "Hope you are enjoying it so far!\p"
	.string "This game, all the characters, the maps,\n"
	.string "the plot, are based on a real life\l"
	.string "friends group.\p"
	.string "Although lots of stories and plotlines\n"
	.string "are based on real events, everything\l"
	.string "has to be taken with a grain of salt.\p"
	.string "I took the freedom to let my\n"
	.string "imagination go in the game I loved since\l"
	.string "I was a childhood.\p"
	.string "Have fun!$"
